# tmux-tabicon - Sample Session-Specific Configuration
#
# This is a sample YAML configuration file for a specific tmux session.
# Copy this file to your themes directory as "[session-name].yml" to apply it
# to a specific session (e.g., "dev.yml" for a session named "dev").

# Color settings
colors:
  # Auto colors: Colors that are automatically assigned to tabs in sequence
  auto:
    - "#2E3440"  # Nord Dark Gray
    - "#3B4252"  # Nord Gray
    - "#434C5E"  # Nord Light Gray
    - "#4C566A"  # Nord Lighter Gray
    - "#81A1C1"  # Nord Blue
    - "#88C0D0"  # Nord Light Blue
  
  # Manual colors: Colors applied to specific tabs based on conditions
  manual:
    - condition: "#{==:#{pane_current_command},npm}"
      color: "#CB4B16"  # Orange for npm
    - condition: "#{==:#{pane_current_command},node}"
      color: "#859900"  # Green for node

# Icon settings
icons:
  # Auto icons: Icons that are automatically assigned to tabs in sequence
  auto:
    - "◆"
  
  # Manual icons: Icons applied to specific tabs based on conditions
  manual:
    - condition: "#{==:#{pane_current_command},npm}"
      icon: "󰎙"
    - condition: "#{==:#{pane_current_command},node}"
      icon: ""

# Normal tab appearance
normal_tab:
  # Title format for normal (inactive) tabs
  title: "#W"
  
  # Formatting for the beginning and end of tabs
  formatting:
    before_first: " "
    before: " "
    after: " "
    after_last: " "
  
  # Style settings for normal tabs
  style:
    base: ""
    icon: "#[fg=#C]"
    title: "#[fg=#D8DEE9]"

# Active tab appearance
active_tab:
  # Title format for the active tab
  title: "#W"
  
  # Formatting for the beginning and end of the active tab
  formatting:
    before_first: " "
    before: " "
    after: " "
    after_last: " "
  
  # Style settings for the active tab
  style:
    base: "#[bg=#C]"
    icon: "#[fg=#ECEFF4]"
    title: "#[fg=#ECEFF4]"

# Character(s) to display between tabs
separator: ""